version: '3.8'

services:
  ipconfigpro:
    build: .
    container_name: ipconfigpro
    networks:
      - linuxpedicom_wp_net
    restart: unless-stopped

networks:
  linuxpedicom_wp_net:
    external: true